service: contentlab

plugins:
    - serverless-offline

provider:
    name: aws
    runtime: nodejs16.x

functions:
    graphql:
        handler: dist/main.graphql
        events:
            -   httpApi:
                    method: POST
                    path: '/{ref}/graphql'
        environment:
            GITHUB_REPOSITORY_OWNER: ${file(./.env.yaml):GITHUB_REPOSITORY_OWNER}
            GITHUB_REPOSITORY_NAME: ${file(./.env.yaml):GITHUB_REPOSITORY_NAME}
            GITHUB_PERSONAL_ACCESS_TOKEN: ${file(./.env.yaml):GITHUB_PERSONAL_ACCESS_TOKEN}
    schema:
        handler: dist/main.schema
        events:
            -   httpApi:
                    method: GET
                    path: '/{ref}/schema'
        environment:
            GITHUB_REPOSITORY_OWNER: ${file(./.env.yaml):GITHUB_REPOSITORY_OWNER}
            GITHUB_REPOSITORY_NAME: ${file(./.env.yaml):GITHUB_REPOSITORY_NAME}
            GITHUB_PERSONAL_ACCESS_TOKEN: ${file(./.env.yaml):GITHUB_PERSONAL_ACCESS_TOKEN}
